# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /authorizations_get for http method type GET 
# RoostTestHash=3b64f22044
# 
# 

# ********RoostGPT********
Feature: List accounts who have access to my account

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * configure headers = { Token: '#(karate.properties['AUTH_TOKEN'])' }
  * url urlBase

Scenario: Successful retrieval of authorizations
  Given path '/authorizations'
  When method get
  Then status 200
  And match response contains { total: '#number', authorizations: '#array' }
  And match each response.authorizations[*] contains { id: '#uuid', name: '#regex(^[\\p{L} .\'-]{1,100}$)', email: '#regex(^(([^<>()[\\]\\\\.,;:\\s@\"]+(\\.[^<>()[\\]\\\\.,;:\\s@\"]+)*)|(\\\".+\\\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$)', createdAt: '#string', updatedAt: '#string' }
  And match response.headers['api-version'] == '1.0.0'

Scenario: Bad Request when parameters are invalid
  Given path '/authorizations'
  And param invalidParam = 'invalid'
  When method get
  Then status 400
  And match response contains { error: '#string', description: '#string' }
  And match response.headers['api-version'] == '1.0.0'

Scenario: Authentication Required when no token provided
  * configure headers = { Token: '' }
  Given path '/authorizations'
  When method get
  Then status 401
  And match response contains { error: '#string', description: '#string' }
  And match response.headers['api-version'] == '1.0.0'
