# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /domestic-vrps/{DomesticVRPId}_get for http method type GET 
# RoostTestHash=83623c009c
# 
# 

# ********RoostGPT********
Feature: Test Domestic VRP Retrieval

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authHeader = {'Authorization': 'Bearer ' + karate.properties['AUTH_TOKEN']}
    * def domesticVRPId = 'xw8v4fog53xz98tofdhycyj8k1cgw3wa1uqc'

  Scenario Outline: Get domestic VRP with valid DomesticVRPId and headers
    Given path '/domestic-vrps/', <DomesticVRPId>
    And headers authHeader
    And header x-fapi-auth-date = <x_fapi_auth_date>
    And header x-fapi-customer-ip-address = <x_fapi_customer_ip_address>
    And header x-fapi-interaction-id = <x_fapi_interaction_id>
    And header x-customer-user-agent = <x_customer_user_agent>
    When method get
    Then status 200
    And assert response.headers['x-fapi-interaction-id'] != null
    And assert response.headers['x-jws-signature'] != null
    And match response == { Data: '#object', Risk: '#object', Links: '#object', Meta: '#object' }

    Examples:
      | DomesticVRPId                                  | x_fapi_auth_date               | x_fapi_customer_ip_address | x_fapi_interaction_id                       | x_customer_user_agent                                                                                   |
      | 'xw8v4fog53xz98tofdhycyj8k1cgw3wa1uqc' | 'Sun, 10 Sep 2017 19:43:31 UTC' | '12.201.45.125'            | 'f8273b70-d5c0-4ef7-b3ba-2b3400fe1956' | 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' |

  Scenario: Get domestic VRP with missing DomesticVRPId
    Given path '/domestic-vrps/'
    And headers authHeader
    When method get
    Then status 400
    And assert response.headers['x-fapi-interaction-id'] != null
    And assert response.headers['x-jws-signature'] != null
    And match response.Errors[*].ErrorCode contains 'UK.OBIE.Field.Missing'

  Scenario: Get domestic VRP with invalid authorization
    Given path '/domestic-vrps/', domesticVRPId
    And header Authorization = 'Bearer invalid_token'
    When method get
    Then status 401
    And assert response.headers['x-fapi-interaction-id'] != null

  Scenario: Get domestic VRP with insufficient permission
    Given path '/domestic-vrps/', domesticVRPId
    And headers authHeader
    And header x-fapi-interaction-id = 'f8273b70-d5c0-4ef7-b3ba-2b3400fe1956'
    When method get
    Then status 403
    And assert response.headers['x-fapi-interaction-id'] != null
    And assert response.headers['x-jws-signature'] != null
    And match response.Errors[*].ErrorCode contains 'UK.OBIE.Resource.InvalidConsentStatus'
