# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /domestic-vrp-consents_post for http method type POST 
# RoostTestHash=acff5e519c
# 
# 

# ********RoostGPT********
Feature: Domestic VRP Consents API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authHeader = { Authorization: '#(karate.properties['AUTH_TOKEN'])' }

  Scenario Outline: Create a domestic VRP consent with valid request payload
    Given path '/domestic-vrp-consents'
    And headers authHeader
    And header x-fapi-auth-date = '<x_fapi_auth_date>'
    And header x-fapi-customer-ip-address = '<x_fapi_customer_ip_address>'
    And header x-fapi-interaction-id = '<x_fapi_interaction_id>'
    And header x-idempotency-key = '<x_idempotency_key>'
    And header x-jws-signature = '<x_jws_signature>'
    And header x-customer-user-agent = '<x_customer_user_agent>'
    And request <request_payload>
    When method post
    Then status 201
    And match responseHeaders contains { 'x-fapi-interaction-id': '#string', 'x-jws-signature': '#string' }
    And match response contains { Data: '#object', Risk: '#object', Links: '#object', Meta: '#object' }
    And assert response.Data.ConsentId != null
    And assert response.Data.CreationDateTime != null
    And assert response.Data.Status == 'AwaitingAuthorisation'
    And assert response.Data.StatusUpdateDateTime != null

    Examples:
      | x_fapi_auth_date                  | x_fapi_customer_ip_address | x_fapi_interaction_id        | x_idempotency_key | x_jws_signature | x_customer_user_agent | request_payload                         |
      | 'Sun, 10 Sep 2017 19:43:31 UTC'   | '12.201.45.125'            | 'f8273b70-d5c0-4ef7-b3ba-2b3400fe1956' | 'igxlwFGgIk015ImMlH4d' | 'eyJodHRwOlwvXC9vcGVuYmFua2luZy5vcmcudWtcL2lhdCI6MTY3MzMzNjQ0OSwiaHR0cDpcL1wvb3BlbmJhbmtpbmcub3JnLnVrXC90YW4iOiJkd3U5OTZ2dzIxOTFmLmNsb3VkZnJvbnQubmV0IiwiY3JpdCI6WyJodHRwOlwvXC9vcGVuYmFua2luZy5vcmcudWtcL2lhdCIsImh0dHA6XC9cL29wZW5iYW5raW5nLm9yZy51a1wvdGFuIiwiaHR0cDpcL1wvb3BlbmJhbmtpbmcub3JnLnVrXC9pc3MiXSwia2lkIjoiZXh0ZXJuYWxfMjAyMiIsInR5cCI6IkpPU0UiLCJodHRwOlwvXC9vcGVuYmFua2luZy5vcmcudWtcL2lzcyI6IkM9R0IsTD1Mb25kb24sTz1IU0JDIEdyb3VwIE1hbmFnZW1lbnQgU2VydmljZXMgTGltaXRlZCxPVT1PcGVuIEJhbmtpbmcgU2hhcmVkIFNlcnZpY2VzLENOPVByZXByb2QtUFNEMi1FeHRlcm5hbC1TaWduYXR1cmUuaHNiYy5jby51ayIsImFsZyI6IlBTMjU2In0..VKQA7mVLNwGPUpAngcvtyumGa9heFwrVSatjlnbnDBpeJnNH9JAo66IqyG0VKFlVE53K-RY47ka7h2ugAAjJnzkGhqxVmvI5K0UdIH7h1ctasTZzU9He6jI-HI5YIR0Mz7myVTDDiP0BHg22WyftzdudaXkgyRJNk8BEHpLWO4kWMuXX6AO6u0rjnsMf1lYuroAe18N2M5XTbWJ0CbJvQfNL_OgPbKpAhzF-tuNoN_9qnYXa2oP-K2GbaW6Chmu4DKIcLX5vswAmXbQuIRfeckou3rk4-VDAmeA1Izm-P1pYsVFAjOVHK1sYHnwbQBY8GMutYsCOn5ZRCtMy1C_IjA' | 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' | read('valid-vrp-consent-request.json') |

  Scenario: Attempt to create a domestic VRP consent with invalid request payload
    Given path '/domestic-vrp-consents'
    And headers authHeader
    And request read('invalid-vrp-consent-request.json')
    When method post
    Then status 400
    And match response contains { Code: '400', Message: '#string', Errors: '#array' }
    And assert response.Errors[0].ErrorCode != null
    And assert response.Errors[0].Message != null
