# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /domestic-vrp-consents/{ConsentId}_get for http method type GET 
# RoostTestHash=be13aa446b
# 
# 

# ********RoostGPT********
Feature: Retrieve a domestic VRP consent

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']

  @GetDomesticVrpConsent
  Scenario Outline: Get Domestic VRP Consent with valid ConsentId
    Given path 'domestic-vrp-consents', <ConsentId>
    And header Authorization = 'Bearer ' + authToken
    And header x-fapi-auth-date = <x-fapi-auth-date>
    And header x-fapi-customer-ip-address = <x-fapi-customer-ip-address>
    And header x-fapi-interaction-id = <x-fapi-interaction-id>
    And header x-customer-user-agent = <x-customer-user-agent>
    When method get
    Then status 200
    And assert response.headers['x-fapi-interaction-id'] != null
    And match response contains { Data: '#object', Risk: '#object', Links: '#object', Meta: '#object' }
    And match response.Data.ConsentId == <ConsentId>

    Examples:
      | ConsentId                              | x-fapi-auth-date                | x-fapi-customer-ip-address | x-fapi-interaction-id               | x-customer-user-agent                                                                 |
      | '9944a9db-2c18-40fc-a611-a28fd85965a1' | 'Sun, 10 Sep 2017 19:43:31 UTC' | '12.201.45.125'            | 'f8273b70-d5c0-4ef7-b3ba-2b3400fe1956' | 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' |

  @GetDomesticVrpConsentInvalid
  Scenario: Get Domestic VRP Consent with invalid ConsentId
    Given path 'domestic-vrp-consents/invalid-consent-id'
    And header Authorization = 'Bearer ' + authToken
    When method get
    Then status 400
    And assert response.headers['x-fapi-interaction-id'] != null
    And match response contains { Code: '#string', Message: '#string', Errors: '#array' }

  @GetDomesticVrpConsentUnauthorized
  Scenario: Get Domestic VRP Consent without Authorization
    Given path 'domestic-vrp-consents/9944a9db-2c18-40fc-a611-a28fd85965a1'
    When method get
    Then status 401
    And assert response.headers['x-fapi-interaction-id'] != null

  @GetDomesticVrpConsentForbidden
  Scenario: Get Domestic VRP Consent with insufficient privileges
    Given path 'domestic-vrp-consents/9944a9db-2c18-40fc-a611-a28fd85965a1'
    And header Authorization = 'Bearer invalid-token'
    When method get
    Then status 403
    And assert response.headers['x-fapi-interaction-id'] != null
    And match response contains { Code: '#string', Message: '#string', Errors: '#array' }

  @GetDomesticVrpConsentMethodNotAllowed
  Scenario: Use an unsupported method to retrieve Domestic VRP Consent
    Given path 'domestic-vrp-consents/9944a9db-2c18-40fc-a611-a28fd85965a1'
    And header Authorization = 'Bearer ' + authToken
    When method post
    Then status 405
    And assert response.headers['x-fapi-interaction-id'] != null

  @GetDomesticVrpConsentNotAcceptable
  Scenario: Request with unacceptable headers for retrieving Domestic VRP Consent
    Given path 'domestic-vrp-consents/9944a9db-2c18-40fc-a611-a28fd85965a1'
    And header Authorization = 'Bearer ' + authToken
    And header Accept = 'application/xml'
    When method get
    Then status 406
    And assert response.headers['x-fapi-interaction-id'] != null

  @GetDomesticVrpConsentUnsupportedMediaType
  Scenario: Request with unsupported media type for retrieving Domestic VRP Consent
    Given path 'domestic-vrp-consents/9944a9db-2c18-40fc-a611-a28fd85965a1'
    And header Authorization = 'Bearer ' + authToken
    And header 'Content-Type' = 'application/xml'
    When method get
    Then status 415
    And assert response.headers['x-fapi-interaction-id'] != null

  @GetDomesticVrpConsentTooManyRequests
  Scenario: Exceeding request rate limit for retrieving Domestic VRP Consent
    Given path 'domestic-vrp-consents/9944a9db-2c18-40fc-a611-a28fd85965a1'
    And header Authorization = 'Bearer ' + authToken
    When method get
    Then status 429
    And assert response.headers['x-fapi-interaction-id'] != null
    And assert response.headers['Retry-After'] != null

  @GetDomesticVrpConsentInternalServerError
  Scenario: Internal server error while retrieving Domestic VRP Consent
    Given path 'domestic-vrp-consents/9944a9db-2c18-40fc-a611-a28fd85965a1'
    And header Authorization = 'Bearer ' + authToken
    When method get
    Then status 500
    And assert response.headers['x-fapi-interaction-id'] != null
    And match response contains { Code: '#string', Message: '#string', Errors: '#array' }
