# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /domestic-vrp-consents/{ConsentId}/funds-confirmation_post for http method type POST 
# RoostTestHash=6b18eb72bb
# 
# 

# ********RoostGPT********
Feature: Confirm availability of funds for a VRP

Background:
  * def urlBase = karate.properties['url.base'] || 'http://localhost:8080'
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario Outline: Confirm funds availability for valid consent with <InstructedAmount> and <Currency>
  Given path '/domestic-vrp-consents/', <ConsentId>, '/funds-confirmation'
  And header Authorization = 'Bearer ' + authToken
  And header x-fapi-interaction-id = <x-fapi-interaction-id>
  And header x-jws-signature = <x-jws-signature>
  And request
  """
  {
    "Data": {
      "ConsentId": "#(ConsentId)",
      "InstructedAmount": {
        "Amount": <InstructedAmount>,
        "Currency": <Currency>
      }
    }
  }
  """
  When method POST
  Then status 201
  And match response contains
  """
  {
    "Data": {
      "FundsConfirmationId": "#string",
      "ConsentId": "#(ConsentId)",
      "CreationDateTime": "#string",
      "FundsAvailableResult": {
        "FundsAvailableDateTime": "#string",
        "FundsAvailable": "Available"
      }
    }
  }
  """

  Examples:
    | ConsentId                              | InstructedAmount | Currency | x-fapi-interaction-id                  | x-jws-signature |
    | 9944a9db-2c18-40fc-a611-a28fd85965a1   | 0.1              | GBP      | f8273b70-d5c0-4ef7-b3ba-2b3400fe1956  | eyJodHRwOlwvXC9vcGVuYmFua2luZy5vcmcudWtcL2lhdCI6MTY3MzMzNjQ0OSwiaHR0cDpcL1wvb3BlbmJhbmtpbmcub3JnLnVrXC90YW4iOiJkd3U5OTZ2dzIxOTFmLmNsb3VkZnJvbnQubmV0IiwiY3JpdCI6WyJodHRwOlwvXC9vcGVuYmFua2luZy5vcmcudWtcL2lhdCIsImh0dHA6XC9cL29wZW5iYW5raW5nLm9yZy51a1wvdGFuIiwiaHR0cDpcL1wvb3BlbmJhbmtpbmcub3JnLnVrXC9pc3MiXSwia2lkIjoiZXh0ZXJuYWxfMjAyMiIsInR5cCI6IkpPU0UiLCJodHRwOlwvXC9vcGVuYmFua2luZy5vcmcudWtcL2lzcyI6IkM9R0IsTD1Mb25kb24sTz1IU0JDIEdyb3VwIE1hbmFnZW1lbnQgU2VydmljZXMgTGltaXRlZCxPVT1PcGVuIEJhbmtpbmcgU2hhcmVkIFNlcnZpY2VzLENOPVByZXByb2QtUFNEMi1FeHRlcm5hbC1TaWduYXR1cmUuaHNiYy5jby51ayIsImFsZyI6IlBTMjU2In0..VKQA7mVLNwGPUpAngcvtyumGa9heFwrVSatjlnbnDBpeJnNH9JAo66IqyG0VKFlVE53K-RY47ka7h2ugAAjJnzkGhqxVmvI5K0UdIH7h1ctasTZzU9He6jI-HI5YIR0Mz7myVTDDiP0BHg22WyftzdudaXkgyRJNk8BEHpLWO4kWMuXX6AO6u0rjnsMf1lYuroAe18N2M5XTbWJ0CbJvQfNL_OgPbKpAhzF-tuNoN_9qnYXa2oP-K2GbaW6Chmu4DKIcLX5vswAmXbQuIRfeckou3rk4-VDAmeA1Izm-P1pYsVFAjOVHK1sYHnwbQBY8GMutYsCOn5ZRCtMy1C_IjA |

Scenario: Confirm funds availability with missing required headers
  Given path '/domestic-vrp-consents/', '9944a9db-2c18-40fc-a611-a28fd85965a1', '/funds-confirmation'
  And header Authorization = 'Bearer ' + authToken
  And request
  """
  {
    "Data": {
      "ConsentId": "9944a9db-2c18-40fc-a611-a28fd85965a1",
      "InstructedAmount": {
        "Amount": 0.1,
        "Currency": "GBP"
      }
    }
  }
  """
  When method POST
  Then status 400
  And match response contains
  """
  {
    "Code": "400",
    "Message": "#string",
    "Errors": "#array"
  }
  """

Scenario: Confirm funds availability with invalid authorization token
  Given path '/domestic-vrp-consents/', '9944a9db-2c18-40fc-a611-a28fd85965a1', '/funds-confirmation'
  And header Authorization = 'Bearer invalid_token'
  And header x-fapi-interaction-id = 'f8273b70-d5c0-4ef7-b3ba-2b3400fe1956'
  And request
  """
  {
    "Data": {
      "ConsentId": "9944a9db-2c18-40fc-a611-a28fd85965a1",
      "InstructedAmount": {
        "Amount": 0.1,
        "Currency": "GBP"
      }
    }
  }
  """
  When method POST
  Then status 401
