# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /hk/payment/simulation_post for http method type POST 
# RoostTestHash=04b1903adc
# 
# 

# ********RoostGPT********
Feature: Hong Kong FPS Payment Simulation API

Background:
  * def urlBase = karate.properties['url.base'] || 'http://localhost:8080'
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario Outline: Valid Hong Kong Bill Payment Simulation with <txnRef>, <merId>, <is_notification_encrypted>, <currency>, <amount>, <suppInfo>
  Given path '/hk/payment/simulation'
  And header Content-Type = 'application/json'
  And header message_encrypt = 'false'
  And header Authorization = 'Bearer ' + authToken
  And request <body>
  When method post
  Then status 200
  And match response contains { api_gw: '#object', response: '#object' }
  And match response.api_gw.messageId == '#string'
  And match response.api_gw.returnCode == '200'
  And match response.api_gw.returnReason == '#string'
  And match response.api_gw.sentTime == '#string'
  And match response.api_gw.responseTime == '#string'
  And match response.response.txnRef == <txnRef>
  And match response.response.proCode == '#string'
  And match response.response.proMsg == '#string'
  And match response.response.currency == <currency>

  Examples:
    | txnRef              | merId          | is_notification_encrypted | currency | amount | suppInfo                 | body                                                                                                             |
    | '0002900F064577105' | 'H099289H441'  | 'Y'                       | 'HKD'    | 2500   | 'Supplementary Info'     | """{ "txnRef": "0002900F064577105", "merId": "H099289H441", "is_notification_encrypted": "Y", "for_bill_payment": { "currency": "HKD", "amount": 2500, "suppInfo": "Supplementary Info" }}""" |

Scenario Outline: Valid Hong Kong Non-bill Payment Simulation with <txnRef>, <merId>, <is_notification_encrypted>, <currency>, <amount>, <suppInfo>
  Given path '/hk/payment/simulation'
  And header Content-Type = 'application/json'
  And header message_encrypt = 'false'
  And header Authorization = 'Bearer ' + authToken
  And request <body>
  When method post
  Then status 200
  And match response contains { api_gw: '#object', response: '#object' }
  And match response.api_gw.messageId == '#string'
  And match response.api_gw.returnCode == '200'
  And match response.api_gw.returnReason == '#string'
  And match response.api_gw.sentTime == '#string'
  And match response.api_gw.responseTime == '#string'
  And match response.response.txnRef == <txnRef>
  And match response.response.proCode == '#string'
  And match response.response.proMsg == '#string'
  And match response.response.currency == <currency>

  Examples:
    | txnRef              | merId          | is_notification_encrypted | currency | amount | suppInfo                 | body                                                                                                                 |
    | '0002900F064577105' | 'H099289H441'  | 'Y'                       | 'HKD'    | 2500   | 'Supplementary Info'     | """{ "txnRef": "0002900F064577105", "merId": "H099289H441", "is_notification_encrypted": "Y", "for_nonbill_payment": { "currency": "HKD", "amount": 2500, "suppInfo": "Supplementary Info" }}""" |

Scenario: Unauthorized request to Hong Kong FPS Payment Simulation API
  Given path '/hk/payment/simulation'
  And header Content-Type = 'application/json'
  And header message_encrypt = 'false'
  When method post
  Then status 403

Scenario: Bad request to Hong Kong FPS Payment Simulation API with missing headers
  Given path '/hk/payment/simulation'
  When method post
  Then status 400

Scenario: Internal server error simulation for Hong Kong FPS Payment Simulation API
  Given path '/hk/payment/simulation'
  And header Content-Type = 'application/json'
  And header message_encrypt = 'false'
  And header Authorization = 'Bearer ' + authToken
  And request """{ "txnRef": "invalid", "merId": "invalid", "is_notification_encrypted": "Y", "for_bill_payment": { "currency": "HKD", "amount": 100, "suppInfo": "Info" }}"""
  When method post
  Then status 500
