# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /hk/refund/simulation_post for http method type POST 
# RoostTestHash=8f41f0dbce
# 
# 

# ********RoostGPT********
Feature: Hong Kong FPS Refund Simulation API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']
  * def headers = { Authorization: '#(authToken)', 'Content-Type': 'application/json', message_encrypt: false }

Scenario Outline: Validate successful refund simulation with various request payloads
  Given path '/hk/refund/simulation'
  And headers headers
  And request 
    """
    <requestBody>
    """
  When method post
  Then status 200
  And match response contains { api_gw: '#object', response: '#object' }
  And match response.api_gw contains { messageId: '#string', returnCode: '200', returnReason: '#string', sentTime: '#string', responseTime: '#string' }
  And match response.response contains { bankTxnId: '#string', proCode: '000000', proMsg: 'Refund Request Submitted' }

  Examples:
    | requestBody |
    | { "txnRef": "0002900F06457710500000001", "merId": "H099289H4410000", "bankTxnId": "HC80502097323467", "txnAmt": 5000, "refundAmt": 4000, "notifyUrl": "https://merchant.com/returnRefundStatus" } |
    | { "txnRef": "0002900F06457710500000002", "merId": "H099289H4410001", "bankTxnId": "HC80502097323468", "txnAmt": 10000, "refundAmt": 5000, "notifyUrl": "https://merchant.com/returnRefundStatus" } |

Scenario Outline: Validate refund simulation with invalid request payloads resulting in bad request
  Given path '/hk/refund/simulation'
  And headers headers
  And request 
    """
    <requestBody>
    """
  When method post
  Then status 400
  And match response contains { api_gw: '#object' }
  And match response.api_gw contains { messageId: '#string', returnCode: '400', returnReason: '#string', sentTime: '#string', responseTime: '#string' }

  Examples:
    | requestBody |
    | { "txnRef": "INVALID_REF", "merId": "H099289H4410000", "bankTxnId": "HC80502097323467", "txnAmt": 5000, "refundAmt": 6000, "notifyUrl": "https://merchant.com/returnRefundStatus" } |
    | { "txnRef": "", "merId": "H099289H4410000", "bankTxnId": "", "txnAmt": 5000, "refundAmt": 4000, "notifyUrl": "" } |

Scenario: Validate refund simulation with missing authorization header resulting in 403 Forbidden
  Given path '/hk/refund/simulation'
  And headers { 'Content-Type': 'application/json', message_encrypt: false }
  And request 
    """
    { "txnRef": "0002900F06457710500000001", "merId": "H099289H4410000", "bankTxnId": "HC80502097323467", "txnAmt": 5000, "refundAmt": 4000, "notifyUrl": "https://merchant.com/returnRefundStatus" }
    """
  When method post
  Then status 403

Scenario: Validate refund simulation with non-existing endpoint resulting in 404 Not Found
  Given path '/hk/refund/simulation/nonexistent'
  And headers headers
  And request 
    """
    { "txnRef": "0002900F06457710500000001", "merId": "H099289H4410000", "bankTxnId": "HC80502097323467", "txnAmt": 5000, "refundAmt": 4000, "notifyUrl": "https://merchant.com/returnRefundStatus" }
    """
  When method post
  Then status 404

Scenario: Validate refund simulation with server error resulting in 500 Internal Server Error
  Given path '/hk/refund/simulation'
  And headers headers
  And request 
    """
    { "txnRef": "0002900F06457710500000001", "merId": "H099289H4410000", "bankTxnId": "HC80502097323467", "txnAmt": 5000, "refundAmt": 4000, "notifyUrl": "https://merchant.com/returnRefundStatus" }
    """
  When method post
  Then status 500
