# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /my/payment/simulation_post for http method type POST 
# RoostTestHash=464c4d2b4b
# 
# 

# ********RoostGPT********
Feature: Malaysia DuitNow Payment Simulation API

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario Outline: Test DuitNow Payment Simulation API with <ContentType> and <MessageEncrypt>
  Given path '/my/payment/simulation'
  And header Content-Type = '<ContentType>'
  And header message_encrypt = <MessageEncrypt>
  And header Authorization = 'Bearer ' + authToken
  And request 
  """
  <RequestBody>
  """
  When method post
  Then status 200
  And match response contains { api_gw: '#object', response: '#object' }
  And match response.api_gw.messageId == '#string'
  And match response.api_gw.returnCode == '200'
  And match response.api_gw.returnReason == '#string'
  And match response.api_gw.sentTime == '#string'
  And match response.api_gw.responseTime == '#string'
  And match response.response.txnRef == '#string'
  And match response.response.proCode == '000000'
  And match response.response.proMsg == 'Transaction Successful'

Examples:
  | ContentType       | MessageEncrypt | RequestBody |
  | 'application/json' | false         | { 'system': { 'is_notification_encrypted': 'Y' }, 'transaction': { 'referenceLabel': '987654321987654321', 'txnChannel': '01', 'txnRef': '1234567890123456789012345' }, 'merchant': { 'merId': 'M437033M7110000', 'storeLabel': '987654321', 'terminalLabel': '987654321' }, 'customer': { 'consumerLabel': '987654321', 'loyaltyNumber': '987654321' }, 'order': { 'amount': 500000, 'currency': 'MYR' }, 'bill': { 'billNumber': '987654321', 'rrn': '987654321', 'rrn2': '987654321' }, 'supplementary': { 'mobileNumber': '987654321', 'purposeOfTransaction': '987654321', 'additionalConsumerDataRequest': 'XXX', 'geoCoordinates': '13.2904027,108.4265113', 'suppInfo': 'Supplementary Info' } } |
