# ********RoostGPT********

# Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4-1106-preview
# 
# Feature file generated for /nobelPrize/{category}/{year}_get for http method type GET 
# RoostTestHash=adfce3f1d2
# 
# 

# ********RoostGPT********
Feature: Nobel Prize Information Retrieval

Background:
  * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
  * url urlBase
  * def authToken = karate.properties['AUTH_TOKEN']

Scenario Outline: Get information about a specific Nobel Prize by category and year
  Given path '2.1/nobelPrize', '<category>', '<year>'
  And header Authorization = 'Bearer ' + authToken
  When method get
  Then status 200
  And match response ==
  """
  {
    "nobelPrize": {
      "awardYear": #number,
      "category": {
        "en": #string,
        "se": #string
      },
      "categoryFullName": {
        "en": #string,
        "se": #string
      },
      "dateAwarded": #string,
      "prizeAmount": #number,
      "prizeAmountAdjusted": #number,
      "topMotivation": {
        "en": #string,
        "se": #string
      },
      "laureates": #array
    }
  }
  """
  And match each response.nobelPrize.laureates contains
  """
  {
    "id": #number,
    "name": {
      "en": #string,
      "se": #string
    },
    "portion": #string,
    "sortOrder": #string,
    "motivation": {
      "en": #string,
      "se": #string
    },
    "links": #array
  }
  """
  Examples:
    | category | year |
    | che      | 1989 |
    | eco      | 1997 |
    | lit      | 2001 |
    | pea      | 2015 |
    | phy      | 2012 |
    | med      | 2020 |

Scenario: Bad request when category or year is invalid
  Given path '2.1/nobelPrize', 'invalid-category', '1900'
  And header Authorization = 'Bearer ' + authToken
  When method get
  Then status 400
  And match response ==
  """
  {
    "code": "400",
    "message": "Bad Request"
  }
  """

Scenario: Resource not found when the Nobel Prize information does not exist
  Given path '2.1/nobelPrize', 'lit', '1800'
  And header Authorization = 'Bearer ' + authToken
  When method get
  Then status 404
  And match response ==
  """
  {
    "code": "404",
    "message": "Resource Not Found"
  }
  """

Scenario: Unprocessable entity when there are semantic errors in the request
  Given path '2.1/nobelPrize', 'lit', 'abcd'
  And header Authorization = 'Bearer ' + authToken
  When method get
  Then status 422
  And match response ==
  """
  {
    "code": "422",
    "message": "Unprocessable Entity"
  }
  """
